### PR TITLE
Add invite link and code to invite members page

### PR DESCRIPTION
**Pull request by robbiecarlton**
screen shot 2015-11-04 at 12 34 07 pm

### CODE REVIEW

**Comment by levity** [comment]
1. "If you would like to invite many people at once..." should stay attached to the form.

2. It's missing some transitional text in between to explain that this is an alternate option and not something related to the form above. In fact it's probably necessary to have headers for both sections now that there are two things on the page, not just one.

Here's my stab at it; @edwardwest, feedback pls.

----

### Send invitations by email
Each recipient will receive an email with a link to join this community that can be used once.

`form goes here`

### Share invitation code
You can also share the code and/or link below to allow people to join your community. You can change this information on the [settings]() page.

`code and link go here`

----

General design principles motivating this suggestion: Put yourself in the shoes of someone who **has never looked at this page before** and think about the questions they would ask. 
* "What will happen if I do this?" (What emotions might be attached to that question?) 
* "How are these things related?" 
* "What do I need to remember?" 

Aspire to make things clear and obvious to that person.

**Comment by edwardwest** [comment]
Agree-- I mocked this up-- what are your thoughts, Lawrence?

_______________________
*Edward West*
mobile 415.225.7335
Facebook <http://www.facebook.com/edwardjwest>  Twitter
<http://www.twitter.com/edwardwest>  LinkedIn
<http://www.linkedin.com/in/edwardwest>

**Comment by levity** [comment]
I'm asking for your feedback on the design suggestions I made in my previous comment. In case it wasn't clear, that was my suggestion for text to use on the page. View the pull request on the web so you can see the Markdown formatting I used.

**Comment by edwardwest** [comment]
ah-- sorry-- My attachment didn't come thru email

image

**Comment by edwardwest** [comment]
maybe this is clearer: 

image

**Comment by levity** [comment]
1. move "If you would like..." up to be with the form
2. let's just reuse the section header style of the user settings page, with a horizontal rule under a short title, and the explanatory paragraph underneath the rule. i think this is what you were aiming for but your mockup looks like it uses a slightly red-tinted gray?
3. spacing after the header's accompanying text should be consistent across the two sections
4. assuming you didn't mean to capitalize "members" in the second header
5. No change button; link to settings page.

**Comment by levity** [comment]
frankly i wonder if it wouldn't be better, less confusing, etc. if we just linked to the invitation code section of the settings page

**Comment by edwardwest** [comment]
1. move "If you would like..." up to be with the form

great

   1. let's just reuse the section header style of the user settings page,
   with a horizontal rule under a short title, and the explanatory paragraph
   underneath the rule. i think this is what you were aiming for but your
   mockup looks like it uses a slightly red-tinted gray?

agreed-- I just hacked it w/photoshop

   1. spacing after the header's accompanying text should be consistent
   across the two sections

agreed-- I just hacked it w/photoshop

   1. assuming you didn't mean to capitalize "members" in the second header

yes

   1. No change button; link to settings page.

when I was showing it to people this invitation to change at the settings
page was the part that confused them. I'm ok with linking to settings page
if it's best, but I didn't do this unconsciously


Overall thoughts:
In general, I really do think this is worth doing, because if you click the
giant "invite members" button, you may be missing out on the best way to
invite members for your community.

Our direct invites often get trapped in people's gmail "social tab" and
aren't always seen



_______________________
*Edward West*
mobile 415.225.7335
Facebook <http://www.facebook.com/edwardjwest>  Twitter
<http://www.twitter.com/edwardwest>  LinkedIn
<http://www.linkedin.com/in/edwardwest>

**Comment by levity** [comment]
> when I was showing it to people this invitation to change at the settings
page was the part that confused them. I'm ok with linking to settings page
if it's best, but I didn't do this unconsciously

interesting, what did people say?

**Comment by edwardwest** [comment]
just something to the effect of-- "wait-- do I need to go to the settings
page to do this? what is that asking me to do?"

Nothing complex

**Comment by robbiecarlton** [comment]
screen shot 2015-11-05 at 4 46 42 pm
screen shot 2015-11-05 at 4 46 59 pm

**Comment by robbiecarlton** [comment]
@levity good?

**Comment by levity** [comment]
Format the headers as sentence case please; otherwise good to go

**Pull request merged**
