### PR TITLE
Add location to post, project and community

### PR DESCRIPTION
**Pull request by robbiecarlton**

### CODE REVIEW

**Comment by levity** [comment]
i can has screenshots?

**Comment by levity** [comment]
code looks good, anyway

**Comment by robbiecarlton** [comment]
I'll post screenshots when it's ready to merge.

**Comment by robbiecarlton** [comment]
Here are the screenshots for desktop. I didn't include mobile, but it all looks as you'd expect.
The only thing I'm not totally keen on is the alignment between the text and the map marker icon on the project view. I fiddled with the css but couldn't get it to look right. LMK if you have any suggestions about that...

screen shot 2015-11-02 at 10 49 18 am
screen shot 2015-11-02 at 10 44 21 am
screen shot 2015-11-02 at 10 44 02 am
screen shot 2015-11-02 at 10 43 32 am
screen shot 2015-11-02 at 10 43 13 am
screen shot 2015-11-02 at 10 42 58 am

**Comment by levity** [comment]
it looks off-center vertically on both the project and the post view. I checked out the branch on my dev env and it looks like the SVG itself is off-center (i.e. if you mouse over the element in Web Inspector, so that the bounding box if the `<i>` is highlighted, the icon is closer to the right). So I would work around this by adding a negative left position in the CSS to the icon.

see if you can get a single value to work independent of font size, using ems (e.g. `left: -0.05em`), and apply it to the `.glyphicon-map-marker` selector; if not, you'll have to adjust it separately for each font size.

**Comment by levity** [comment]
putting location in the toolbar of the About tab seems strange to me. better to put it in the body and get rid of the toolbar entirely, i think.

**Comment by levity** [comment]
other than those two things, seems :ship:-shape

**Comment by robbiecarlton** [comment]
Ok, I'll deal with the horizontal alignment. I hadn't noticed it but see it now.
I was actually referring to the vertical alignment. maybe it's fine, but to me it feels like the text should be on line with the bottom of the pin

**Comment by levity** [comment]
Vertical alignment could be tweaked too, but do it for all the icons in that section in that case.

**Comment by robbiecarlton** [comment]
If it's cool with you I'm gonna merge and put vertical alignment on the backburner. I'm not finding anything that works better than what's there.

**Comment by levity** [comment]
ok

**Pull request merged**
