### PR TITLE
Public post ux

### PR DESCRIPTION
**Pull request by levity**

### CODE REVIEW

**Comment by levity** [comment]
@robbiecarlton want to review?

**Comment by robbiecarlton** [comment]
@levity - code looks good. Browserify failed when I tried to run it locally, with this:
```
Error: Cannot find module 'medium.js/node_modules/undo.js/undo' from '/Users/robbiecarlton/work/hylo/hylo-frontend/src/js/app/directives'
```
Is hat important?

**Comment by robbiecarlton** [comment]
actually getting that error on master branch as well

**Comment by levity** [comment]
were you able to test this locally?

**Comment by robbiecarlton** [comment]
Yup, tested with a public post, worked great

**Comment by edwardwest** [comment]
Nice one, guys!

_______________________
*Edward West*
mobile 415.225.7335
Facebook <http://www.facebook.com/edwardjwest>  Twitter
<http://www.twitter.com/edwardwest>  LinkedIn
<http://www.linkedin.com/in/edwardwest>

**Pull request merged**
