### PR TITLE
(WIP) Social sharing

### PR DESCRIPTION
**Pull request by robbiecarlton**

### CODE REVIEW

**Comment by robbiecarlton** [comment]
Working on mobile then i'll post screenshots

**Comment by robbiecarlton** [comment]
screen shot 2015-11-11 at 4 21 04 pm
screen shot 2015-11-11 at 4 20 56 pm 1
screen shot 2015-11-11 at 4 20 42 pm
screen shot 2015-11-11 at 4 20 36 pm

**Comment by robbiecarlton** [comment]
@levity can I merge?

**Comment by levity** [comment]
that icon means [escape](http://apple.stackexchange.com/questions/8738/what-is-this-symbol-it-is-listed-as-menu-shortcut) to me... maybe [this one](https://thenounproject.com/search/?q=share&i=55610) instead?

**Comment by levity** [comment]
looks good otherwise

**Comment by robbiecarlton** [comment]
screen shot 2015-11-12 at 3 27 56 pm

**Comment by levity** [comment]
:+1: :+1: :+1:

**Pull request merged**
