### PR TITLE
add invite members and settings buttons to community banner

### PR DESCRIPTION
**Pull request by robbiecarlton**

### CODE REVIEW

**Comment by robbiecarlton** [comment]
@levity could you take a look at this when you have a minute? Everything is in place, but the buttons are not clickable. When I move them to other parts of the page they work. Seems like something to do with css/html

**Comment by levity** [comment]
Try bumping z-index and setting position relative -- use the web
inspector's shift-cmd-c mode to see what does get selected when you attempt
to click on them

**Comment by robbiecarlton** [comment]
thanks.
z index did it
Desktop 1
Desktop 2
Mobile Uncentered 1
Mobile Uncentered 2
Mobile Centered 1
Mobile Centered 2

**Comment by levity** [comment]
could you narrow the spacing between the two buttons to match what we've
done on the edit profile page? it's a little large at the moment relative
to the spacing between the buttons and the edges of their container.

thanks for the screenshots!

**Comment by levity** [comment]
you can merge after the spacing change

**Pull request merged**
